apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  releaseName: sealed-secrets
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: sealed-secrets-repo
      version: "2.16.1"
  interval: 5m
  values:
    nameOverride: sealed-secrets
    fullnameOverride: sealed-secrets
    crd:
      # crd.create: `true` if the crd resources should be created
      create: true
      # crd.keep: `true` if the sealed secret CRD should be kept when the chart is deleted
      keep: false
    resource:
      requests:
        cpu: 100m
        memory: 200m
      limit:
        cpu: 200m
        memory: 300m