---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-system-reconciler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kube-system-reconciler
  namespace: kube-system
rules:
  - apiGroups: ['*']
    resources: ['*']
    verbs: ['*']
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kube-system-reconciler
  namespace: kube-system
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: kube-system-reconciler
subjects:
- kind: ServiceAccount
  name: kube-system-reconciler
  namespace: kube-system