apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bootstrap
spec:
  project: default
  source:
    path: ./environments/staging-cluster
    repoURL: 'https://github.com/phucnguyen25392/argo-devops'
    targetRevision: master
  destination:
    namespace: argocd
    server: 'https://kubernetes.default.svc'