apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: metrics-server
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: metrics-server
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 7.2.13
  helm:
    releaseName: metrics-server
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd