apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: sealed-secrets
    repoURL: https://bitnami-labs.github.io/sealed-secrets
    targetRevision: 2.5.0
    helm:
      releaseName: sealed-secrets
      valuesObject:
        resource:
          limits:
            cpu: 250m
            memory: 350m
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system