apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: ingress-nginx
  namespace: kube-system
spec:
  releaseName: ingress-nginx
  chart:
    spec:
      chart: nginx-ingress
      sourceRef:
        kind: HelmRepository
        name: nginx-stable-repo
        namespace: kube-system
      version: 2.0.0
  interval: 5m
  values:
    controller:
      serviceMonitor:
        enabled: true
        labels:
          release: "prometheus"
      service:
        type: ClusterIP
      enableLatencyMetrics: true
      ingressClass:
        create: true
        setAsDefaultIngress: true
        name: "nginx"
    prometheus:
      create: true
